import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add Firebase core import
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:tonetribe/tribecreationpage.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter bindings are initialized
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Initialize Firebase with platform-specific options
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: CreateMusicTribePage(), // Directly using CreateMusicTribePage as the home page
    );
  }
}